### PR TITLE
Mbed OS 5.15.0

### PR DESCRIPTION
**Pull request by teetak01**

### CODE REVIEW

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/499/)
***
**Test summary:**
Executed: 14
Failed: 0
Skipped: 0
Errors: 2

**Failed test cases:**
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_U201-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/499)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/507/)
***

**Test summary:**
Executed: 16
Failed: 2
Skipped: 0
Errors: 4

**Failed test cases:**
UBLOX_EVK_ODIN_W2-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2.UBLOX_EVK_ODIN_W2 - [Timeout: Did not find Endpoint Name within 600 seconds]_
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_U201-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_R412M-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
UBLOX_C030_R412M-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
DISCO_L475VG_IOT01A-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2.DISCO_L475VG_IOT01A - [PUT:Unexpected HTTP result code 502 while expecting [200]]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/507)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/508/)
***

**Test summary:**
Executed: 16
Failed: 2
Skipped: 0
Errors: 4

**Failed test cases:**
UBLOX_EVK_ODIN_W2-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2.UBLOX_EVK_ODIN_W2 - [Timeout: Did not find Endpoint Name within 600 seconds]_
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_U201-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_R412M-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
UBLOX_C030_R412M-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
DISCO_L475VG_IOT01A-ARM-TCP: _ExampleAppCloudTest01_Rel1_2.DISCO_L475VG_IOT01A - [GET:Unexpected HTTP result code 502 while expecting [200]]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/508)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/509/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/509)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request closed without merging**
