### PR TITLE
Tweaks to fix FOTA for EP_AGORA

### PR DESCRIPTION
**Pull request by trowbridgec**
This PR tweaks the configuration for the Embedded Planet `EP_AGORA` target to use the build from [mbed-bootloader](https://github.com/ARMmbed/mbed-bootloader) for the `EP_AGORA` target and fixes issues with FOTA support.

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by trowbridgec** [comment]
@linlingao @ARMmbed/team-embeddedplanet @maclobdell

**Comment by trowbridgec** [comment]
bump

**Comment by teetak01** [comment]
We are going to the get the Firmware update test probably today to this repository, so it might be good to rerun those tests with that, especially as this is FOTA specific fix.

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/574/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/574)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
Can this be rebased?

**Comment by trowbridgec** [comment]
@teetak01 done!

**Comment by teetak01** [comment]
@trowbridgec still out-of-date?

**Comment by trowbridgec** [comment]
@teetak01 Whoops, sorry about that...please check again.

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/580/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/580)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
