### PR TITLE
add more targets to be tested by ci

### PR DESCRIPTION
**Pull request by JammuKekkonen**

### CODE REVIEW

**Comment by JammuKekkonen** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/562/)
***

**Test summary:**
Executed: 28
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/562)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by JammuKekkonen** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/563/)
***

**Test summary:**
Executed: 50
Failed: 0
Skipped: 0
Errors: 14
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/563)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by JammuKekkonen** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/564/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/564)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by JammuKekkonen** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/565/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/565)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by JammuKekkonen** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/566/)
***

**Test summary:**
Executed: 50
Failed: 0
Skipped: 0
Errors: 14

**Failed test cases:**
NUCLEO_F429ZI-GCC_ARM-TCP: _NUCLEO_F429ZI-GCC_ARM-TCP.dev-client-tests - [test teardown failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
UBLOX_EVK_ODIN_W2-GCC_ARM-TCP: _UBLOX_EVK_ODIN_W2-GCC_ARM-TCP.dev-client-tests - [test teardown failure]_
UBLOX_EVK_ODIN_W2-ARM-TCP: _UBLOX_EVK_ODIN_W2-ARM-TCP.dev-client-tests - [test setup failure]_
UBLOX_EVK_ODIN_W2-ARM-TCP: _UBLOX_EVK_ODIN_W2-ARM-TCP.dev-client-tests - [test setup failure]_
UBLOX_EVK_ODIN_W2-ARM-TCP: _UBLOX_EVK_ODIN_W2-ARM-TCP.dev-client-tests - [test setup failure]_
UBLOX_EVK_ODIN_W2-ARM-TCP: _UBLOX_EVK_ODIN_W2-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F411RE-ARM-TCP: _NUCLEO_F411RE-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F411RE-ARM-TCP: _NUCLEO_F411RE-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F411RE-ARM-TCP: _NUCLEO_F411RE-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F411RE-ARM-TCP: _NUCLEO_F411RE-ARM-TCP.dev-client-tests - [test setup failure]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/566)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by JammuKekkonen** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/567/)
***

**Test summary:**
Executed: 33
Failed: 0
Skipped: 0
Errors: 5

**Failed test cases:**
NUCLEO_F429ZI-GCC_ARM-TCP: _NUCLEO_F429ZI-GCC_ARM-TCP.dev-client-tests - [test teardown failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
NUCLEO_F429ZI-ARM-TCP: _NUCLEO_F429ZI-ARM-TCP.dev-client-tests - [test setup failure]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/567)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by JammuKekkonen** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/568/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/568)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
