### PR TITLE
Upgrade components

### PR DESCRIPTION
**Pull request by teetak01**
### Summary of changes 

- Updated PDMC library to 4.11.1 version.
- Updated Mbed OS to 6.15.1 version.
- Updated python test-library to latest version supporting manifest v1 version.

[x] I confirm this contribution is my own and I agree to license it with Apache 2.0.

[x] I confirm the moderators may change the PR before merging it in.

For new board enablements only:

[] I confirm the board is [Mbed Enabled](https://www.mbed.com/en/about-mbed/mbed-enabled/introduction/) and passes the Mbed Enabled test set.

[] I confirm the contribution has been tested properly and the tests results for [TESTS](https://github.com/ARMmbed/mbed-os-example-pelion/tree/master/TESTS) are attached.

[] I confirm `mbed-os.lib` and `mbed-cloud-client.lib` hashes or the content in folders `mbed-os` and `mbed-cloud-client` were not modified in order to pass the tests.

- Maintainers of this repository update the Mbed OS and Client hashes.
- Please report any issues through issues in relevant repositories.

### CODE REVIEW

**Comment by teetak01** [comment]
run-ci

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/785/)
***

**Test summary:**
Executed: 24
Failed: 4
Skipped: 0
Errors: 0

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d7116092c00000000000100100172 - failed_connector_channel_update]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d7116030900000000000100100170 - failed_connector_channel_update]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d71171cc200000000000100100174 - failed_connector_channel_update]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d7116f1ef00000000000100100173 - failed_connector_channel_update]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/785)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/786/)
***

**Test summary:**
Executed: 24
Failed: 4
Skipped: 0
Errors: 0

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d7139f5ca0000000000010010017e - failed_connector_channel_update]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d7139f2a10000000000010010017d - failed_connector_channel_update]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d713b28cb00000000000100100180 - failed_connector_channel_update]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [AssertionError: Timeout while waiting update campaign device state to reach deployed. Campaign: 017d713cfc7800000000000100100182 - failed_connector_channel_update]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/786)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: ABORTED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/787/)
posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/788/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/788)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/789/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/789)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/790/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/790)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
