### PR TITLE
CI testing

### PR DESCRIPTION
**Pull request by anttiylitokola**

### CODE REVIEW

**Comment by anttiylitokola** [comment]
testing

**Comment by anttiylitokola** [comment]
testing

**Comment by anttiylitokola** [comment]
testing

**Comment by anttiylitokola** [comment]
testing

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/4/)
***[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/4)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/

**Comment by anttiylitokola** [comment]
testing

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/5/)
***[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/5)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/

**Comment by anttiylitokola** [comment]
testing

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/6/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/6)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/

**Comment by anttiylitokola** [comment]
testing

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/7/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/7)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/

**Comment by anttiylitokola** [comment]
testing

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/8/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/8)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/

**Comment by anttiylitokola** [comment]
testing

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/9/)
***

**Test summary:**
Executed: 7
Failed: 1
Skipped: 0
Errors: 1

**Failed test cases:**
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
NUCLEO_F411RE-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2.NUCLEO_F411RE - [PUT:Unexpected HTTP result code 410 while expecting [200]]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/9)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion-antyli01/

**Comment by anttiylitokola** [comment]
run-ci

**Comment by anttiylitokola** [comment]
run-ci

**Comment by anttiylitokola** [comment]
run-ci

**Comment by anttiylitokola** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/503/)
***

**Test summary:**
Executed: 7
Failed: 0
Skipped: 0
Errors: 1

**Failed test cases:**
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/503)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/504/)
***

**Test summary:**
Executed: 14
Failed: 1
Skipped: 0
Errors: 2

**Failed test cases:**
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_U201-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
NUCLEO_F411RE-ARM-TCP: _ExampleAppCloudTest01_Rel1_2.NUCLEO_F411RE - [PUT:Unexpected HTTP result code 410 while expecting [200]]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/504)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request closed without merging**
