### PR TITLE
Add target C030_R412M

### PR DESCRIPTION
**Pull request by wajahat-ublox**
Added support for C030_R412M board. Example is running and tests are passing as well.
Some issues are under discussion [here](https://github.com/ARMmbed/mbed-os-example-pelion/issues/16#issuecomment-531127374).
[2019-09-13_160248.zip](https://github.com/ARMmbed/mbed-os-example-pelion/files/3615065/2019-09-13_160248.zip)

### CODE REVIEW

**Comment by teetak01** [comment]
@wajahat-ublox can you rebase this and update the README?

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/496/)
***
**Failed to build following targets:**
UBLOX_C030_R412M-ARM-TCP
UBLOX_C030_R412M-GCC_ARM-TCP
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/496)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
@wajahat-ublox I tested the compilation locally at it passed, so this mostly just requires rebase.

**Comment by wajahat-ublox** [comment]
@teetak01 
I have rebased and pushed to my branch however this PR is not updated, any idea what went wrong?

https://github.com/wajahat-ublox/mbed-os-example-pelion/tree/target_c030_r412m

**Comment by JanneKiiskila** [comment]
https://github.com/wajahat-ublox/mbed-os-example-pelion/tree/target_c030_r412m gives 404, so perhaps we do not have access to it? I can't access https://github.com/wajahat-ublox/mbed-os-example-pelion/ either.

**Comment by wajahat-ublox** [comment]
@JanneKiiskila My fork is still showing as private as i forked when this repo was private but now this repo is public?

**Comment by wajahat-ublox** [comment]
@JanneKiiskila I have made it public still PR is not getting updated.

**Comment by teetak01** [comment]
Closing. Already merged via #66

**Pull request closed without merging**
