### PR TITLE
Add Renesas GR-PEACH and GR-LYCHEE support

### PR DESCRIPTION
**Pull request by toyowata**
Revised from https://github.com/ARMmbed/mbed-os-example-pelion/pull/83

[GR-PEACH]

External SPI flash (memory mapped) : 8MB
RAM : 10MB
Connectivity : Ethernet

kvstore : memory mapped flash (48 kB)
Update storage : memory mapped flash (4MB)

[GR-LYCHEE]

External SPI flash (memory mapped) : 8MB
RAM : 3MB
Connectivity : Wi-Fi (ESP32)

kvstore : memory mapped flash (48 kB)
Update storage : memory mapped flash (4MB)

mbed-bootloader configs : https://github.com/ARMmbed/mbed-bootloader/pull/56

### GR_PEACH (RZ_A1H)
```
============================== 4 passed in 31.78s ==============================
2020-01-15 11:05:10,999:tests.conftest:MainThread:INFO: -----  TEST RESULTS SUMMARY  -----
2020-01-15 11:05:11,000:tests.conftest:MainThread:INFO: [ check the complete fail reasons and code locations from this log or html report ]
2020-01-15 11:05:11,000:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_01_get_device_id - (0.861s)
2020-01-15 11:05:11,000:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_02_put_resource - (4.739s)
2020-01-15 11:05:11,000:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_03_get_resource - (1.710s)
2020-01-15 11:05:11,001:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_04_subscribe_resource - (2.451s)
```
### GR_LYCHEE
```
============================== 4 passed in 39.15s ==============================
2020-01-15 10:58:02,240:tests.conftest:MainThread:INFO: -----  TEST RESULTS SUMMARY  -----
2020-01-15 10:58:02,240:tests.conftest:MainThread:INFO: [ check the complete fail reasons and code locations from this log or html report ]
2020-01-15 10:58:02,241:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_01_get_device_id - (0.772s)
2020-01-15 10:58:02,241:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_02_put_resource - (4.831s)
2020-01-15 10:58:02,242:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_03_get_resource - (1.839s)
2020-01-15 10:58:02,242:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_04_subscribe_resource - (3.470s)
```

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by JanneKiiskila** [comment]
Ah, some conflicts that need resolving in the README.md and mbed_app.json -files @toyowata , please.

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/577/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/577)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by toyowata** [comment]
@JanneKiiskila @teetak01 I rebased to master.

**Comment by JanneKiiskila** [comment]
Thanks, time to merge @teetak01!

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/578/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/578)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
