### PR TITLE
Support NUMAKER_IOT_M263A (re-raise)

### PR DESCRIPTION
**Pull request by ccli8**
This PR is re-raised to support NUMAKER_IOT_M263A.

**Note1**: #43 breaks for some unknown reason. This PR is re-raised to replace it.

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by ccli8** [comment]
Attach last part of firmware update:

```
Update progress = 99%
Update progress = 100%
Counter 94

Mbed Bootloader
[DBG ] Update active firmware
[DBG ] Erase active application
[DBG ] Write header
[DBG ] Copy application
[DBG ] Verify application
[DBG ] New active firmware is valid
booting...

Application ready
Connect to network
Network initialized, connected with IP 192.168.8.100

Start developer flow
Create resources
Register Pelion Device Management Client

Counter 1
Counter 2
Client registered.
Account ID: 016ff984f7634a68f16ae84400000000
Endpoint name: 0170563f98f1000000000001001b97e3
Device ID: 0170563f98f1000000000001001b97e3
```

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/604/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/604)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
