### PR TITLE
Add Seeed Arch-MAX support

### PR DESCRIPTION
**Pull request by toyowata**
Internal Flash : 512kB
RAM : 192kB
Connectivity : Ethernet

kvstore : internal flash
Update storage : SD card

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by MarceloSalazar** [comment]
Platform in raas-cam1
Pending: ISGTESTINF-4581

**Comment by teetak01** [comment]
Needs rebase + README update.

**Comment by toyowata** [comment]
@teetak01 I updated the readme and rebased.

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/576/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/576)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
