### PR TITLE
README.md: Adds instructions how to obtain bootloader-details

### PR DESCRIPTION
**Pull request by VeijoPesonen**
Fixes ARMmbed/mbed-bootloader#23

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by VeijoPesonen** [comment]
@ wajahat-ublox for your information.

**Comment by VeijoPesonen** [comment]
> Instead is best to point developers to the corresponding `json` file that will contain the information.

I can't find the same information from the corresponding json file

**Comment by teetak01** [comment]
This is the manual way of generating the hash. Alternatively you can find the information as part of bootloader releases https://github.com/ARMmbed/mbed-bootloader/releases/tag/v4.1.1

There is a text-file which contain this information.

**Comment by MarceloSalazar** [comment]
Are you saying this is a kind of random value that's generated at compile time?

**Comment by wajahat-ublox** [comment]
> 
> 
> Are you saying this is a kind of random value that's generated at compile time?
> It would be great to understand the logic behinds this.

If i am not wrong, this is the address where bootloader lies. It is was earlier printed on serial but was later removed to reduce memory footprint. Now the only way is by reading it from .map file of the image.

**Comment by VeijoPesonen** [comment]
> 
> 
> Are you saying this is a kind of random value that's generated at compile time?
> It would be great to understand the logic behinds this.

Please see the bootloader documentation about the [subject](https://github.com/ARMmbed/mbed-bootloader/blob/master/README.md#bootloader-information)

**Comment by MarceloSalazar** [comment]
@VeijoPesonen thanks for the link to the docs. It looks we're still referring to information generated on the serial port.
I'm ok to leave the comments on the docs on how to find out the hash info. In the future, I'll be looking at generating this automatically after the compile/link process.

**Comment by teetak01** [comment]
@MarceloSalazar that would most likely be a feature request for Mbed CLI to provide such functionality.

**Comment by teetak01** [comment]
@VeijoPesonen can you rebase this?

**Comment by VeijoPesonen** [comment]
Rebased.

**Pull request merged**
