### PR TITLE
Make get_res writable

### PR DESCRIPTION
**Pull request by esajaa**
Having writable get_res allows to reset the counter.

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/522/)
***

**Test summary:**
Executed: 16
Failed: 0
Skipped: 0
Errors: 4

**Failed test cases:**
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_U201-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_R412M-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
UBLOX_C030_R412M-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/522)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/523/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/523)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
