### PR TITLE
add cy8cproto_062_4343w with tdb external

### PR DESCRIPTION
**Pull request by maclobdell**
### Summary of changes

Adds support for Cypress PSoC 62 Prototyping board (CY8CPROTO-062-4343W).

This configuration adds usage of Quad SPI Flash for storage. This frees up internal memory.

[Yes] I confirm this contribution is my own and I agree to license it with Apache 2.0.

[Yes] I confirm the moderators may change the PR before merging it in.

For new board enablements only:

[Yes] I confirm the board is [Mbed Enabled](https://www.mbed.com/en/about-mbed/mbed-enabled/introduction/) and passes the Mbed Enabled test set.

[Yes] I confirm the contribution has been tested properly and the tests results for [TESTS](https://github.com/ARMmbed/mbed-os-example-pelion/tree/master/TESTS) are attached.
[pytest-cy8cproto.txt](https://github.com/ARMmbed/mbed-os-example-pelion/files/4625800/pytest-cy8cproto.txt)

[Yes] I confirm `mbed-os.lib` and `mbed-cloud-client.lib` hashes or the content in folders `mbed-os` and `mbed-cloud-client` were not modified in order to pass the tests.

### Details
- I could not get file system for external kvstore working (plus I heard that file system for kvstore is deprecated anyway).  So I configured it for `tbd_external`. This seems to work except for the known issue below.  
- To build the bootloader, I had to use a slightly modified version of mbed-os and mbed-bootloader. This is pushed to my repo at https://github.com/maclobdell/mbed-bootloader,
on branch `cy8cproto-bootloader-build-4.1.3`. This is a temporary location and I will work to get it supported in the official `mbed-bootloader`  repo.
- I included the bootloader in binary form instead of hex to avoid gaps in the bootloader memory footprint which can occur on the platform due to dual core layout. This avoids any potential issues with the build tools not merging the bootloader correctly.

### Known Issues
- Currently the device gets a new ID every time the application is re-flashed. This needs to be debugged.
- I know that the configuration is a bit messy. I used absolute addresses and sizes instead of formulas. If that is a problem, I can go back and change them to formulas where possible

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by maclobdell** [comment]
See attached log related to the known issue I mentioned. Please let me know if you have any suggestion. I can make a change and push a new branch.  This is with trace set to 'TRACE_LEVEL_INFO_WARN'
[cy8cproto_trace_log.txt](https://github.com/ARMmbed/mbed-os-example-pelion/files/4625876/cy8cproto_trace_log.txt)

This is after a reset. There are several errors, but I don't know if they are recoverable errors (normal), or not (real problem).

**Comment by teetak01** [comment]
Can you rebase the PR? It seems to be out-of-date?

OTherwise the PR looks fine. The new device ID with flashing is known issue in our backlog, probably related on Device key generation. Something we can not do explicitly before Mbed OS 6.

**Comment by maclobdell** [comment]
I just rebased the PR.

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/632/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 4
Errors: 0

**Failed to build following targets:**
CY8CPROTO_062_4343W-ARM-TCP
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/632)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
@maclobdell can you check the linker issues? There is quite a bit of warnings and some crypto-errors.

**Comment by maclobdell** [comment]
I just updated the branch with fix for linker issues, updates to readme, and slight re-ordering of the config section for this board. I tested firmware update after building with the Arm compiler and it worked fine. Please re-test!

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/633/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/633)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
