### PR TITLE
Add bl + config for Nucleo L4R5ZI with ESP8266.

### PR DESCRIPTION
**Pull request by JammuKekkonen**

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by yogpan01** [comment]
@JammuKekkonen This should proabably be rebased since 5.15 is already merged.

**Comment by JammuKekkonen** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/527/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/527)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
