### PR TITLE
Update pelion-e2e-python-test-library for using manifest tool >= v2.1.0

### PR DESCRIPTION
**Pull request by moshe-shahar**
### Summary of changes 

- Update README.md
- Update *pelion-e2e-python-test-library.lib* to v0.2.9

[x] I confirm this contribution is my own and I agree to license it with Apache 2.0.

[x] I confirm the moderators may change the PR before merging it in.

For new board enablements only:

[] I confirm the board is [Mbed Enabled](https://www.mbed.com/en/about-mbed/mbed-enabled/introduction/) and passes the Mbed Enabled test set.

[] I confirm the contribution has been tested properly and the tests results for [TESTS](https://github.com/ARMmbed/mbed-os-example-pelion/tree/master/TESTS) are attached.

[] I confirm `mbed-os.lib` and `mbed-cloud-client.lib` hashes or the content in folders `mbed-os` and `mbed-cloud-client` were not modified in order to pass the tests.

- Maintainers of this repository update the Mbed OS and Client hashes.
- Please report any issues through issues in relevant repositories.

### CODE REVIEW

**Review by jenia81 — APPROVED** [review]

**Comment by jenia81** [comment]
@teetak01 is there anyone else who should review it?
Do you know how to run the PR checks here?

**Comment by teetak01** [comment]
build-only

**Comment by jenia81** [comment]
@teetak01 seems that CI still didn't run, can you take a look on this

**Comment by moshe-shahar** [comment]
build-only

**Comment by moshe-shahar** [comment]
build-only

**Comment by moshe-shahar** [comment]
Currently, the CI is not triggered for PRs from a fork.

**Comment by moshe-shahar** [comment]
replaced with https://github.com/ARMmbed/mbed-os-example-pelion/pull/155

**Comment by moshe-shahar** [comment]
build-only

**Pull request closed without merging**
