### PR TITLE
Update to Mbed OS 5.15.5

### PR DESCRIPTION
**Pull request by teetak01**
https://github.com/ARMmbed/mbed-os/releases/tag/mbed-os-5.15.5

### CODE REVIEW

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/667/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0

**Failed to build following targets:**
NUMAKER_PFM_NUC472-GCC_ARM-TCP
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/667)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
@MarceloSalazar any idea why NUMAKER_PFM_NUC472-GCC_ARM-TCP no longer fits on target with 5.15.5?

`/usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: region `RAM_INTERN' overflowed by 800 bytes`

**Comment by MarceloSalazar** [comment]
Sorry I don't know.
@ARMmbed/team-nuvoton can you please have a look and comment?

**Comment by ccli8** [comment]
@teetak01 NUMAKER_PFM_NUC472 has 64KiB internal RAM and 1MiB external RAM. The internal RAM has overflowed. I will adjust memory layout to fit this program.

**Comment by cyliangtw** [comment]
It seems the path of MBEDTLS_ENTROPY_NV_SEED encounter overflow of internal-SRAM.
If I use MBEDTLS_ENTROPY_HARDWARE_ALT, it's fine to build in GCC tool-chain. ( `https://os.mbed.com/teams/Nuvoton/code/mbed-os-example-pelion//file/d147172e94b5/mbed_app.json/ `)

**Comment by cyliangtw** [comment]
@teetak01, @MarceloSalazar 
NUMAKER_PFM_NUC472-GCC_ARM build fail issue could be resolved by fixing NUC472 SD buffer alignment issue in [mbed-os PR #13512](https://github.com/ARMmbed/mbed-os/pull/13512)

**Pull request closed without merging**
