### PR TITLE
Update to Device Management Client 4.6.0

### PR DESCRIPTION
**Pull request by teetak01**
## New features

Added support for [Parsec](https://parallaxsecond.github.io/parsec-book/index.html), the Trusted Platform Module for Linux.

### Device Management Client

-  Removed the upper limit (900 seconds before expiration) for calculating the registration update timer expiration. Now, the timer uses 75% of the lifetime.
-  Changed the notification handler to send a notification only when crossing the "less than" or "greater than" notification threshold values.
-  Added support for the Parsec open-source initiative. It provides a platform-agnostic interface for calling the secure storage and operation services of a Trusted Platform Module (TPM) on Linux.
-  Optimized application reconnection handling.
   - Previously, the reconnection timer seed was randomized between 10 and 100 seconds. Now, the base value is platform-specific and you can control it using the `PAL_DEFAULT_RTT_ESTIMATE` macro (estimated round-trip time for the network).
      - Mbed OS defaults to 10 seconds.
      - NXP and Renesas SDKs default to 5 seconds.
      - Linux defaults to 3 seconds.
   - You can now optimize the client recovery behaviour based on the expected network performance (latency and bandwidth).
- Added handling for `MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE` during handshake. This allows the client to recover and fall back to bootstrap if the LwM2M credentials are invalid.
- Fixed a segmentation failure caused by a POST operation with payload to an unregistered LwM2M resource.
- Improved handling of timeouts during network and TLS/DTLS operations to avoid unnessary fallbacks to re-bootstrapping.

### Platform Adaptation Layer (PAL)

-  PAL SST APIs were removed. The new adaptation layer for Secure Storage is KVStore APIs.
-  Deprecated the `MBED_CLIENT_RECONNECTION_INTERVAL` macro. An application that needs to control the CoAP retransmission intervals should now define `PAL_DEFAULT_RTT_ESTIMATE`.
-  Deprecated the `MBED_CONF_MBED_CLIENT_DTLS_PEER_MAX_TIMEOUT` macro. An application that needs to control the DTLS intervals should now define `PAL_DEFAULT_RTT_ESTIMATE`.
-  Linux: Fixed handling of PIPE errors during socket handling that resulted in unwanted application termination instead of raising an error. Now, PIPE errors result in SSL handshake errors.

Release notes can be found from:

https://cloud.mbed.com/docs/current/release-notes/device-management-client.html

### CODE REVIEW

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/665/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/665)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/666/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/666)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Review by ristohuhtala — APPROVED** [review]

**Pull request merged**
