### PR TITLE
Update to Device Management Client 4.2.0 release and Mbed OS 5.15.0

### PR DESCRIPTION
**Pull request by teetak01**

### CODE REVIEW

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/512/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/512)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/513/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0

**Failed to build following targets:**
K64F-GCC_ARM-TCP
DISCO_L475VG_IOT01A-GCC_ARM-TCP
K66F-GCC_ARM-TCP
K66F-ARM-TCP
K64F-ARM-TCP
NUCLEO_F429ZI-ARM-TCP
UBLOX_EVK_ODIN_W2-GCC_ARM-TCP
UBLOX_C030_U201-GCC_ARM-TCP
NUCLEO_F429ZI-GCC_ARM-TCP
NUCLEO_F411RE-GCC_ARM-TCP
UBLOX_EVK_ODIN_W2-ARM-TCP
UBLOX_C030_U201-ARM-TCP
UBLOX_C030_R412M-GCC_ARM-TCP
UBLOX_C030_R412M-ARM-TCP
NUCLEO_F411RE-ARM-TCP
DISCO_L475VG_IOT01A-ARM-TCP
EP_AGORA-GCC_ARM-TCP
EP_AGORA-ARM-TCP
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/513)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/514/)
***

**Test summary:**
Executed: 16
Failed: 0
Skipped: 0
Errors: 4

**Failed to build following targets:**
EP_AGORA-GCC_ARM-TCP
EP_AGORA-ARM-TCP

**Failed test cases:**
UBLOX_C030_U201-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_U201-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_U201.json does not exist.]_
UBLOX_C030_R412M-GCC_ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
UBLOX_C030_R412M-ARM-TCP: _ExampleAppCloudTest01_Rel1_2 - [Execution configuration file ./pdmc-jenkins/test-configs/mbed-os-example-pelion-configs/tc_UBLOX_C030_R412M.json does not exist.]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/514)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/515/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/515)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: ABORTED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/516/)
posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
