### PR TITLE
Update to 0.2.3 version of Pelion E2E python test library

### PR DESCRIPTION
**Pull request by teetak01**
### Summary of changes 

- Support for testing with linux binary.
- Subscription test updated.
- Set manifest-tool's default path to working directory.
- Minor error situation improvements.
<!--

### CODE REVIEW

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/596/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 4
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/596)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/597/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 4
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/597)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
