### PR TITLE
Support NUMAKER_PFM_NUC472 (re-raise)

### PR DESCRIPTION
**Pull request by ccli8**
This PR is re-raised to support NUMAKER_PFM_NUC472.

**Note1**: #39 breaks for some unknown reason. This PR is re-raised to replace it.

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by teetak01** [comment]
@ccli8 could you retain the PR template and provide the E2E test-results for this board as part of the PR?

**Comment by ccli8** [comment]
@teetak01 Configured `PELION_CLOUD_API_KEY` as documented, I run E2E test but meet error with `Limit for the number of API keys exceeded (2).` How can I resolve it?

```
2020-01-30 16:16:02.592  [   DEBUG]   Initializing Cloud API fixture    (cloud_fixtures.py:35)
2020-01-30 16:16:03.991  [   DEBUG]   Request headers: {'User-Agent': 'pelion-e2e-test-library', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-type': 'application/json', 'Authorization': 'Bearer ak_SKIPSKIPSKIPSKIPSKIPSKIP', 'Content-Length': '38'}    (rest_api.py:95)
2020-01-30 16:16:03.992  [   DEBUG]   Request body: {"name": "pelion_e2e_dynamic_api_key"}    (rest_api.py:96)
2020-01-30 16:16:03.994  [   DEBUG]   Response headers: {'Date': 'Thu, 30 Jan 2020 08:16:03 GMT', 'Content-Type': 'application/json', 'Content-Length': '248', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=10886400; includeSubDomains; preload', 'X-Request-ID': '00005e3290c39ec8b2b0a22000000003', 'Access-Control-Allow-Origin': '*', 'Vary': 'Origin', 'Access-Control-Expose-Headers': 'X-Request-ID,Content-Length,Content-Disposition', 'Set-Cookie': 'TS017f188d=01c6170234640cd3cdc317ae81e4c51a98f106f7ef998798894cbb592242a14b9b8c8686cc8285f7bc9d0ef040944daadb8dfc9653; Path=/'}    (rest_api.py:97)
2020-01-30 16:16:03.994  [   DEBUG]   Response: [403]  POST /v3/api-keys    (rest_api.py:98)
2020-01-30 16:16:03.994  [   DEBUG]   Response text: {"fields":[{"name":"apikey-count","message":"Limit for the number of API keys exceeded (2)."}],"object":"error","code":403,"type":"account_limit_exceeded","message":"Account limit has been exceeded.","request_id":"00005e3290c39ec8b2b0a22000000003"}    (rest_api.py:99)
2020-01-30 16:16:04.092  [   ERROR]   ERROR: create_api_key failed!
Expected result 201 -> actual response was: 403

Response body: {"fields":[{"name":"apikey-count","message":"Limit for the number of API keys exceeded (2)."}],"object":"error","code":403,"type":"account_limit_exceeded","message":"Account limit has been exceeded.","request_id":"00005e3290c39ec8b2b0a22000000003"}

Response headers: {'Date': 'Thu, 30 Jan 2020 08:16:03 GMT', 'Content-Type': 'application/json', 'Content-Length': '248', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=10886400; includeSubDomains; preload', 'X-Request-ID': '00005e3290c39ec8b2b0a22000000003', 'Access-Control-Allow-Origin': '*', 'Vary': 'Origin', 'Access-Control-Expose-Headers': 'X-Request-ID,Content-Length,Content-Disposition', 'Set-Cookie': 'TS017f188d=01c6170234640cd3cdc317ae81e4c51a98f106f7ef998798894cbb592242a14b9b8c8686cc8285f7bc9d0ef040944daadb8dfc9653; Path=/'}    (utils.py:64)
2020-01-30 16:16:04.162  [    INFO]   -----  TEST RESULTS SUMMARY  -----    (conftest.py:72)
2020-01-30 16:16:04.163  [    INFO]   [ check the complete fail reasons and code locations from this log or html report ]    (conftest.py:73)
2020-01-30 16:16:04.163  [    INFO]   [FAILED] - ::test_03_get_resource - (1.502s)    (conftest.py:78)
2020-01-30 16:16:04.163  [    INFO]   E           AssertionError: ERROR: create_api_key failed!    (conftest.py:83)
2020-01-30 16:16:04.164  [    INFO]   E           Expected result 201 -> actual response was: 403    (conftest.py:83)
2020-01-30 16:16:04.164  [    INFO]   E               (conftest.py:83)
2020-01-30 16:16:04.164  [    INFO]   E ---8<--- Error log summary cut down to few lines, check full log above or from html report ---8<---
    (conftest.py:85)
```

**Comment by teetak01** [comment]
@ccli8 currently the test-tool requires one API key to start the tests, and then it will dynamically create&delete another key to guarantee unique notification channel for the test-run.

I asked the tools-team to allow disabling this feature. If you can delete one of your API-keys on your account, the test should then work. Accounts normally have a limit of 2 API-keys.

**Comment by ccli8** [comment]
@teetak01 Thanks for your information. I try under my Online Compiler account, which has 4 API key space for the Pelion E2E tests. So it is resolved.

But I meet another issue on my Windows 10 environment. I've [created a ticket](https://github.com/ARMmbed/pelion-e2e-python-test-library/issues/15) to address it

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/591/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/591)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by yogpan01** [comment]
@teetak01 can this now be merged?

**Comment by teetak01** [comment]
@ccli8 can you rebase this and confirm that you have verified that at least Firmware update passes on this board. I can then merge this in. We need to get the windows-issues resolved on the test-framework seperately.

**Comment by ccli8** [comment]
@teetak01 Do rebase. The firmware update process is OK.

```
Update progress = 99%
Update progress = 100%

Mbed Bootloader
[DBG ] Update active firmware
[DBG ] Erase active application
[DBG ] Write header
[DBG ] Copy application
[DBG ] Verify application
[DBG ] New active firmware is valid
booting...

Application ready
Connect to network
mac address ee-87-00-28-70-66
PHY ID 1:0x243
PHY ID 2:0xc54
Network initialized, connected with IP 192.168.0.100

Start developer flow
Create resources
Register Pelion Device Management Client

Counter 1
Client registered.
Account ID: 016ff984f7634a68f16ae84400000000
Endpoint name: 0170527c25360000000000010012bdb9
Device ID: 0170527c25360000000000010012bdb9

Counter 2
```

**Comment by teetak01** [comment]
build-only

**Comment by teetak01** [comment]
Thank you @ccli8

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/603/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/603)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
