### PR TITLE
Add ESP32 Wi-Fi driver for Renesas GR-LYCHEE

### PR DESCRIPTION
**Pull request by toyowata**
[x] I confirm this contribution is my own and I agree to license it with Apache 2.0.
[x] I confirm the moderators may change the PR before merging it in.

### Summary of changes 

I added the ESP32 Wi-Fi driver which accidentally missed in the PR https://github.com/ARMmbed/mbed-os-example-pelion/pull/96

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by JanneKiiskila** [comment]
> Should the esp32.provide-default be set to true for this target to enable the driver?

Yes it should. GR_LYCHEE does not seem to have Ethernet at all, it only has ESP32.

**Comment by toyowata** [comment]
@teetak01 @JanneKiiskila 
The GR-LYCHEE board has on-board ESP32 module and the esp32.provide-default is defined here: https://github.com/ARMmbed/esp32-driver/blob/d6bd83f8710b4c475b3cce101d8b2c77e17feaf6/mbed_lib.json#L49

## E2E test-results (same as [here](https://github.com/ARMmbed/mbed-os-example-pelion/pull/96#issue-366656342))
```
============================== 4 passed in 39.15s ==============================
2020-01-15 10:58:02,240:tests.conftest:MainThread:INFO: -----  TEST RESULTS SUMMARY  -----
2020-01-15 10:58:02,240:tests.conftest:MainThread:INFO: [ check the complete fail reasons and code locations from this log or html report ]
2020-01-15 10:58:02,241:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_01_get_device_id - (0.772s)
2020-01-15 10:58:02,241:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_02_put_resource - (4.831s)
2020-01-15 10:58:02,242:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_03_get_resource - (1.839s)
2020-01-15 10:58:02,242:tests.conftest:MainThread:INFO: [passed] - dev-client-tests.py::test_04_subscribe_resource - (3.470s)
```

**Comment by teetak01** [comment]
I really do not like that practice. ISM43362 is also silently enabling it for some boards. It would be better that application would always have to enable the driver if it actually wants to use it.

Well, this is one reason we use the COMPONENT formalism as these would cause suprise-issues if some board is used with different network-stack than some driver is expecting.

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/581/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/581)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
