### PR TITLE
Revert "Add cy8cproto 062 4343w"

### PR DESCRIPTION
**Pull request by JammuKekkonen**
Reverts ARMmbed/mbed-os-example-pelion#70

This target no longer compiles after update to Mbed OS 5.15

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by JammuKekkonen** [comment]
build-only

**Comment by JammuKekkonen** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/520/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/520)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
