### PR TITLE
Test PR for testing CI

### PR DESCRIPTION
**Pull request by esajaa**
### Summary of changes 

[] I confirm this contribution is my own and I agree to license it with Apache 2.0.

[] I confirm the moderators may change the PR before merging it in.

For new board enablements only:

[] I confirm the board is [Mbed Enabled](https://www.mbed.com/en/about-mbed/mbed-enabled/introduction/) and passes the Mbed Enabled test set.

[] I confirm the contribution has been tested properly and the tests results for [TESTS](https://github.com/ARMmbed/mbed-os-example-pelion/tree/master/TESTS) are attached.

[] I confirm `mbed-os.lib` and `mbed-cloud-client.lib` hashes or the content in folders `mbed-os` and `mbed-cloud-client` were not modified in order to pass the tests.

- Maintainers of this repository update the Mbed OS and Client hashes.
- Please report any issues through issues in relevant repositories.

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/638/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 4

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [test setup failure]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [test setup failure]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/638)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/639/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/639)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/640/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 4

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [test setup failure]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [test setup failure]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/640)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/641/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0

**Failed to build following targets:**
K64F-ARM-TCP
K66F-GCC_ARM-TCP
K64F-GCC_ARM-TCP
K66F-ARM-TCP
NUCLEO_F429ZI-ARM-TCP
NUCLEO_F429ZI-GCC_ARM-TCP
UBLOX_EVK_ODIN_W2-GCC_ARM-TCP
GR_LYCHEE-ARM-TCP
RZ_A1H-ARM-TCP
ARCH_MAX-ARM-TCP
NUMAKER_PFM_NUC472-ARM-TCP
EP_AGORA-ARM-TCP
GR_LYCHEE-GCC_ARM-TCP
NUMAKER_PFM_M487-ARM-TCP
NUMAKER_IOT_M487-ARM-TCP
UBLOX_C030_U201-ARM-TCP
NUCLEO_F411RE-ARM-TCP
UBLOX_C030_R412M-ARM-TCP
DISCO_L496AG-ARM-TCP
EP_AGORA-GCC_ARM-TCP
NUMAKER_IOT_M263A-ARM-TCP
DISCO_L496AG-GCC_ARM-TCP
UBLOX_EVK_ODIN_W2-ARM-TCP
NUCLEO_F411RE-GCC_ARM-TCP
NUMAKER_IOT_M487-GCC_ARM-TCP
UBLOX_C030_R412M-GCC_ARM-TCP
UBLOX_C030_U201-GCC_ARM-TCP
NUCLEO_L4R5ZI-ARM-TCP
RZ_A1H-GCC_ARM-TCP
DISCO_L475VG_IOT01A-ARM-TCP
NUMAKER_PFM_NUC472-GCC_ARM-TCP
NUMAKER_PFM_M487-GCC_ARM-TCP
NUMAKER_IOT_M263A-GCC_ARM-TCP
DISCO_L475VG_IOT01A-GCC_ARM-TCP
WIO_3G-GCC_ARM-TCP
WIO_3G-ARM-TCP
NUCLEO_H743ZI2-ARM-TCP
ARCH_MAX-GCC_ARM-TCP
NUCLEO_L4R5ZI-GCC_ARM-TCP
NUCLEO_H743ZI2-GCC_ARM-TCP
WIO_BG96-GCC_ARM-TCP
NUCLEO_F767ZI-ARM-TCP
WIO_BG96-ARM-TCP
UHURU_RAVEN-ARM-TCP
CY8CPROTO_062_4343W-ARM-TCP
UHURU_RAVEN-GCC_ARM-TCP
NUCLEO_F767ZI-GCC_ARM-TCP
CY8CPROTO_062_4343W-GCC_ARM-TCP
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/641)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/642/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 4

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [test setup failure]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [test setup failure]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/642)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/644/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 4

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [test setup failure]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [test setup failure]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [test setup failure]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/644)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/645/)
***

**Test summary:**
Executed: 24
Failed: 4
Skipped: 0
Errors: 0

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/645)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/646/)
***

**Test summary:**
Executed: 24
Failed: 4
Skipped: 0
Errors: 0

**Failed test cases:**
K64F-GCC_ARM-TCP: _K64F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
K64F-ARM-TCP: _K64F-ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
K66F-GCC_ARM-TCP: _K66F-GCC_ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
K66F-ARM-TCP: _K66F-ARM-TCP.dev-client-tests - [AssertionError: Didn't find new active firmware is valid in 900 s]_
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/646)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/647/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/647)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/649/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0

**Failed to build following targets:**
K64F-ARM-TCP
K64F-GCC_ARM-TCP
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/649)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/650/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0

**Failed to build following targets:**
K64F-ARM-TCP
K64F-GCC_ARM-TCP
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/650)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/651/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/651)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: FAILED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/652/)
***

**Test summary:**
Executed: 0
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/652)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/653/)
***

**Test summary:**
Executed: 12
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/653)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/654/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 0
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/654)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by esajaa** [comment]
Finished testing, closing this pull request

**Pull request closed without merging**
