### PR TITLE
Add support for EP_AGORA

### PR DESCRIPTION
**Pull request by trowbridgec**
This PR adds support for the Embedded Planet `EP_AGORA` target which uses cellular for connectivity and external SPIF for firmware update storage.

This PR is also a re-do of #21 which was broken once the repo was switched to public.

### CODE REVIEW

**Comment by iot-pdmc** [comment]
Thanks for your changes.
@ARMmbed/pdmc-integrators please review.

**Comment by trowbridgec** [comment]
@teetak01 I created this new PR to add our target. As #21 is broken (I still keep getting a Server Error from GitHub), are you able to close it?

@ARMmbed/team-embeddedplanet @maclobdell

**Comment by trowbridgec** [comment]
@teetak01 I was able to close #21 from my phone, so no need anymore.

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/505/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/505)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
build-only

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/506/)
***
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/506)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
