### PR TITLE
Update to Pelion Device Management Client 4.3.0

### PR DESCRIPTION
**Pull request by teetak01**

### CODE REVIEW

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: ABORTED](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/594/)
posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Comment by teetak01** [comment]
run-ci

**Comment by iot-pdmc** [comment]
# [Test run: SUCCESS](https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/595/)
***

**Test summary:**
Executed: 24
Failed: 0
Skipped: 4
Errors: 0
[Build artifacts](http://pdmc-ci.s3-website-eu-west-1.amazonaws.com/?prefix=jenkins-ci/mbed-os-example-pelion/595)

posted-by-tag: https://jenkins-client.isgtesting.com/job/mbed-os-example-pelion/

**Pull request merged**
